import type { Configuration } from 'electron-builder'

const configuration: Configuration = {
  appId: 'com.ordicab.desktop',
  productName: 'Ordicab',
  // Stamped into the Windows .exe version resource (Details tab) and the macOS
  // bundle. `${author}` would resolve to "Ordicab" too, but spelling it out
  // keeps the legal notice stable regardless of package.json edits.
  copyright: `© ${new Date().getFullYear()} Ordicab`,
  // The app ships only French and English. Trimming Electron's bundled locales
  // drops ~50 unused .lproj folders from the macOS bundle (smaller, cleaner
  // "Languages" list in Get Info).
  electronLanguages: ['en', 'fr'],
  directories: {
    output: 'out/make',
    buildResources: 'build'
  },
  files: [
    '!**/.vscode/*',
    '!src/*',
    '!electron.vite.config.{js,ts,mjs,cjs}',
    '!{.eslintcache,eslint.config.mjs,.prettierignore,.prettierrc.yaml,dev-app-update.yml,CHANGELOG.md,README.md}',
    '!{.env,.env.*,.npmrc,pnpm-lock.yaml}',
    '!{tsconfig.json,tsconfig.node.json,tsconfig.web.json}'
  ],
  // Native binaries (.node, .dll, .dylib, .so) and model files cannot live
  // inside the asar archive — they must be on the real filesystem so the
  // OS loader and onnxruntime can mmap them.
  asarUnpack: [
    'resources/**',
    '**/node_modules/onnxruntime-node/**',
    '**/node_modules/@huggingface/transformers/**'
  ],
  extraResources: [
    { from: 'build/license_fr.txt', to: 'legal/license_fr.txt' },
    { from: 'build/license_en.txt', to: 'legal/license_en.txt' },
    { from: 'resources/tessdata/fra.traineddata', to: 'tessdata/fra.traineddata' },
    { from: 'resources/tessdata/eng.traineddata', to: 'tessdata/eng.traineddata' }
    // ONNX models (NER, bge-m3) are NOT bundled — they are downloaded at first
    // launch into {userData}/models by modelProvisioningService. This keeps the
    // installer ~300 MB lighter and lets the embedding model change without a
    // re-release.
  ],
  mac: {
    icon: 'build/icon.icns',
    category: 'public.app-category.productivity',
    target: [
      { target: 'dmg', arch: ['arm64'] },
      { target: 'zip', arch: ['arm64'] }
    ],
    entitlementsInherit: 'build/entitlements.mac.plist',
    artifactName: '${productName}-${version}-mac-${arch}.${ext}',
    // Electron 39 floor; surfaces the requirement in Finder/Get Info and blocks
    // launch on unsupported macOS instead of crashing.
    minimumSystemVersion: '11.0',
    notarize: true
  },
  dmg: {
    artifactName: '${productName}-${version}-mac-${arch}.${ext}',
    // Volume name shown when the .dmg is mounted. Defaults to
    // "${productName} ${version}"; drop the version for a cleaner Finder title.
    title: '${productName}',
    // Branded drag-to-install window. The background (with its arrow) is drawn to
    // match these icon centers — keep them in sync with scripts/generate-brand-assets.mjs.
    // electron-builder auto-loads build/background@2x.png for retina.
    background: 'build/background.png',
    window: { width: 540, height: 380 },
    iconSize: 100,
    contents: [
      { x: 140, y: 230, type: 'file' },
      { x: 400, y: 230, type: 'link', path: '/Applications' }
    ]
  },
  win: {
    icon: 'build/icon.ico',
    target: [{ target: 'nsis', arch: ['x64'] }]
  },
  nsis: {
    artifactName: '${productName}-${version}-win-${arch}-setup.${ext}',
    shortcutName: '${productName}',
    uninstallDisplayName: '${productName}',
    createDesktopShortcut: 'always',
    createStartMenuShortcut: true,
    oneClick: false,
    allowToChangeInstallationDirectory: false,
    // Ordicab stores legal dossiers under userData — never wipe them on
    // uninstall/upgrade. This is the default, but spelled out given the stakes.
    deleteAppDataOnUninstall: false,
    license: 'build/license_fr.txt',
    // Brand the installer chrome. Without these, electron-builder falls back to
    // its generic NSIS artwork. Icons reuse the app .ico; the sidebar (164×314)
    // is shown on the welcome/finish pages and the header (150×57) on inner
    // pages — all generated by scripts/generate-brand-assets.mjs.
    installerIcon: 'build/icon.ico',
    uninstallerIcon: 'build/icon.ico',
    installerHeaderIcon: 'build/icon.ico',
    installerSidebar: 'build/installerSidebar.bmp',
    uninstallerSidebar: 'build/uninstallerSidebar.bmp',
    installerHeader: 'build/installerHeader.bmp'
  },
  npmRebuild: false,
  publish: [
    {
      provider: 'github',
      owner: 'jmtanguy',
      repo: 'Ordicab',
      releaseType: 'release'
    }
  ]
}

export default configuration
